<a href="https://colab.research.google.com/github/shriramrahul7/fmml2021/blob/main/10_Problem_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Madagascar problem

In [2]:
import numpy as np

In [13]:
A = np.array([[20, 122, 20], [35,180, 35],[50, 220, 65], [70, 300, 30]], dtype=np.float16)
x = np.array([[0.05], [0.002], [0.02]], dtype=np.float16)

In [4]:
# 4x3 . 3x1 = 4x1

In [14]:
y = np.matmul(A,x) - 4.0
y

array([[-2.355 ],
       [-1.189 ],
       [ 0.2383],
       [ 0.699 ]], dtype=float16)

In [19]:
Z = np.hstack((A,y))

In [20]:
Z

array([[ 2.000e+01,  1.220e+02,  2.000e+01, -2.355e+00],
       [ 3.500e+01,  1.800e+02,  3.500e+01, -1.189e+00],
       [ 5.000e+01,  2.200e+02,  6.500e+01,  2.383e-01],
       [ 7.000e+01,  3.000e+02,  3.000e+01,  6.992e-01]], dtype=float16)

In [21]:
def RankArray(A,x):
  y = np.dot(A,x) - 4.0
  L = np.hstack((A,y))
  return L

In [25]:
data = RankArray(A,x)
print(data)


[[ 2.000e+01  1.220e+02  2.000e+01 -2.355e+00]
 [ 3.500e+01  1.800e+02  3.500e+01 -1.189e+00]
 [ 5.000e+01  2.200e+02  6.500e+01  2.383e-01]
 [ 7.000e+01  3.000e+02  3.000e+01  6.992e-01]]


In [27]:
ll = [(data[i]) for i, j in enumerate(data[:, -1]) if j >= 0]

print("The Risk Prone people are :")

for i in ll:
  print(i)

The Risk Prone people are :
[ 50.     220.      65.       0.2383]
[ 70.    300.     30.      0.699]
